name: Try mesen
on:
  push:
    branches: [ mesen-ci ]
  workflow_dispatch:
jobs:
  package:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install dependencies.
        run: |
          sudo apt-get update
          sudo apt-get -y install mono-complete libsdl2-2.0 gnome-themes-standard libgtk2.0-0 xvfb

      - name: Install mesen.
        run: |
          curl -Lo mesen.zip https://www.mesen.ca/download.php
          unzip mesen.zip
          chmod +x Mesen.exe
          # Keep mesen from popping up a configuration wizard.
          touch settings.xml

      - name: Run mesen.
        run: |
          echo 'emu.stop(1)' > script.lua
          xvfb-run mono Mesen.exe --testrunner script.lua
